#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

set -eux

bazel run //hs-github-tools/tools:hub-settings -- \
  "$SCRIPT_DIR/org.yaml" \
  "$SCRIPT_DIR/repos.yaml" \
  "$@"
