_common:
  editRepo: &editRepo
    private: false
    has_issues: true
    has_projects: false
    has_wiki: false
    default_branch: "master"
    delete_branch_on_merge: true
    is_template: false
    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    archived: false

experimental:
  editRepo:
    <<: *editRepo
    name: "experimental"
    description: "Experimental - Anyone can submit anything in here"
    homepage: "https://toktok.ltd"
