#!/usr/bin/env bash

REMOTE=""
BRANCH="${1-master}"

if (echo "$BRANCH" | grep ':' >/dev/null); then
  REMOTE="$(echo "$BRANCH" | grep -o '^[^:]*')"
  BRANCH="$(echo "$BRANCH" | grep -o '[^:]*$')"
  REMOTE="$(git remote -v | grep ":$REMOTE/.* (push)" | grep -o '^\S*')"
fi

set -eux

case "$BRANCH" in
  --continue)
    git rebase --continue
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    ;;

  master)
    git fetch upstream
    git checkout master
    git merge upstream/master
    git push
    exit 0
    ;;

  *)
    if [ -n "$REMOTE" ] && ! (git branch | grep "^..$BRANCH\$" >/dev/null); then
      git checkout --track "$REMOTE/$BRANCH"
    else
      git checkout "$BRANCH"
    fi
    git rebase upstream/master
    ;;
esac

git push --force
git checkout master
git branch -d "$BRANCH"
