#!/bin/sh

set -eu

REMOTE=""
BRANCH="${1-master}"

if (echo "$BRANCH" | grep ':' > /dev/null); then
  REMOTE="$(echo "$BRANCH" | grep -o '^[^:]*')"
  BRANCH="$(echo "$BRANCH" | grep -o '[^:]*$')"
  REMOTE="$(git remote -v | grep ":$REMOTE/.* (push)" | grep -o '^\S*')"
fi

if [ -n "$REMOTE" ]; then
  git checkout --track "$REMOTE/$BRANCH"
else
  git checkout $BRANCH
fi

git push upstream "$BRANCH:master"
git sync
git branch -d "$BRANCH"
git push origin ":$BRANCH"
